version: '1.0'

services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: musyimi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5430:5432"
    networks:
      - db
    restart: unless-stopped

  app:
    container_name: user-api
    image: mwenekware/user-api
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user
    ports:
      - "8088:8080"
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

