server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8096
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://dpg-cm9f9jmn7f5s73dhggg0-a.oregon-postgres.render.com:5432/user_t4tb
    username: musyimi
    password: pJL5ocBGCy4qbx0RcBWNSPebqiUagHTj

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true
    show-sql: false



